// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetToolList() {
  return window['go']['main']['App']['GetToolList']();
}
